"""
build_cold_refs.py
==================
Cold CAESAR ILS-Applied reference 파일 재생성 (올바른 FWHM 적용).

Background
----------
The original Cold FWHM_Analysis.txt was generated by a buggy algorithm that
reported FWHM = 75-87 nm.  Direct measurement from the Hg lamp raw data shows
the actual Cold instrument FWHM is ~3.4 nm (sigma ~1.44 nm).

This script:
  1. Loads the Cold wavelength calibration (2048 pixels, 399-494 nm)
  2. Measures the correct sigma from the Hg lamp CSV (adaptive half-max method)
  3. Writes a corrected FWHM_Analysis_CORRECTED.txt
  4. Loads each raw cross-section from C:\\LGH\\Absorption cross-section by lgh\\원본
  5. Applies Dynamic-ILS convolution with the correct sigma profile
  6. Saves corrected Ref_*.dat files to D:\\CAESAR cold\\
  7. Also regenerates sigma(cold)_corrected.xlsx

Run:  py calibration/build_cold_refs.py
"""

from __future__ import annotations
import os, sys
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from scipy.optimize import curve_fit

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────
COLD_DIR          = r"D:\CAESAR cold"
RAW_XS_DIR        = r"C:\LGH\Absorption cross-section by lgh\원본"
HG_CSV            = r"D:\CAESAR cold\2026 5월 06 10_46_46.csv"
WAVE_CAL_TXT      = r"D:\CAESAR cold\Calib_20260507_Hg_399-494nm_Poly2.txt"
OUT_FWHM_FILE     = os.path.join(COLD_DIR, "FWHM_Analysis_CORRECTED.txt")

# Raw cross-section files
RAW_XS = {
    "NO2":     os.path.join(RAW_XS_DIR, "NO2_Vandaele(2002)_294K_384-725nm(vis-dilut5).txt"),
    "CHOCHO":  os.path.join(RAW_XS_DIR, "CHOCHO_Volkamer(2005)_296K_250.031-526.168nm(0.001nm).txt"),
    "O4":      os.path.join(RAW_XS_DIR, "O4_ThalmanVolkamer(2013)_293K_335.749-600.802nm.txt"),
}
# H2O from HITRAN (downloaded to hitran_data folder)
HITRAN_DIR = r"C:\LGH\hitran_data"

# Literature FWHM of source cross-sections (nm) — for variance subtraction
# NO2 Vandaele: 0.01 nm FWHM; CHOCHO Volkamer: ~0.001 nm; O4 ThalmanVolkamer: measured
LIT_FWHM = {
    "NO2":    0.01156,   # Vandaele 2002 resolution
    "CHOCHO": 0.01,      # Volkamer 2005 ~0.001 nm step → ~0.01 nm FWHM
    "O4":     0.0,       # ThalmanVolkamer: high-res
    "H2O-HITRAN": 0.0,  # HITRAN line-by-line
}

# ─────────────────────────────────────────────────────────────────────────────
# Step 1: Load wavelength calibration
# ─────────────────────────────────────────────────────────────────────────────
print("=== Step 1: Loading wavelength calibration ===")
with open(WAVE_CAL_TXT, "r", encoding="utf-8", errors="replace") as f:
    data_lines = [l.strip() for l in f if l.strip() and not l.strip().startswith("#")]
wavelengths = np.array([float(l) for l in data_lines])
print(f"  {len(wavelengths)} pixels, {wavelengths[0]:.3f} ~ {wavelengths[-1]:.3f} nm")

# ─────────────────────────────────────────────────────────────────────────────
# Step 2: Load Hg lamp spectrum and measure FWHM
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Step 2: Measuring Cold ILS FWHM from Hg lamp ===")
df_hg = pd.read_csv(HG_CSV)
frames = [
    df_hg[(df_hg["Frame"] == fr) & (df_hg["Row"] == 0)]
    .sort_values("Column")["Intensity"].values
    for fr in sorted(df_hg["Frame"].unique())
]
avg_spec = np.mean(frames, axis=0)
print(f"  Hg spectrum: {len(avg_spec)} pixels, avg {frames[0].shape[0]} per frame × {len(frames)} frames")


def _gaussian(x, a, mu, sigma, offset):
    return a * np.exp(-0.5 * ((x - mu) / sigma) ** 2) + offset


def measure_fwhm(peak_pixel: int, spec: np.ndarray, wl: np.ndarray):
    """Returns (fwhm_px, fwhm_nm, sigma_nm) using adaptive window."""
    pk = int(np.clip(peak_pixel, 0, len(spec) - 1))
    ctx = spec[max(0, pk - 200): min(len(spec), pk + 201)]
    baseline = float(np.percentile(ctx, 10))
    amplitude = float(spec[pk]) - baseline
    if amplitude <= 0:
        return None, None, None
    half_level = baseline + amplitude * 0.5

    left = pk
    while left > 0 and spec[left] > half_level:
        left -= 1
    right = pk
    while right < len(spec) - 1 and spec[right] > half_level:
        right += 1

    half_width = max(right - pk, pk - left, 1)
    window = max(15, min(300, int(half_width * 1.5)))
    s, e = max(0, pk - window), min(len(spec), pk + window + 1)
    x_d = np.arange(s, e, dtype=float)
    y_d = spec[s:e]

    sigma_guess = max(0.5, min(half_width / 2.3548, window * 0.8))
    p0 = [amplitude, float(pk), sigma_guess, baseline]
    lo = [0.0, float(s), 0.3, -np.inf]
    hi = [np.inf, float(e), float(window), np.inf]
    try:
        popt, _ = curve_fit(_gaussian, x_d, y_d, p0=p0, bounds=(lo, hi), maxfev=8000)
    except Exception as exc:
        print(f"    Gaussian fit failed at px {pk}: {exc}")
        return None, None, None

    _, mu, sigma, _ = popt
    fwhm_px = 2.3548 * abs(sigma)
    mu_i = int(np.clip(round(mu), 1, len(wl) - 2))
    dispersion = (wl[mu_i + 1] - wl[mu_i - 1]) / 2.0
    fwhm_nm = fwhm_px * dispersion if dispersion > 0 else None
    sigma_nm = fwhm_nm / 2.3548 if fwhm_nm else None
    return fwhm_px, fwhm_nm, sigma_nm


hg_peak_pixels = [107, 741]   # 404 nm and 433 nm Hg lines
fwhm_records = {}
for pk in hg_peak_pixels:
    fpx, fnm, snm = measure_fwhm(pk, avg_spec, wavelengths)
    if fpx:
        print(f"  Peak col {pk}: FWHM = {fpx:.1f} px = {fnm:.3f} nm  (sigma = {snm:.4f} nm)")
        fwhm_records[float(pk)] = {"fwhm_px": fpx, "fwhm_nm": fnm, "sigma_nm": snm}

valid_fwhms_nm = [v["fwhm_nm"] for v in fwhm_records.values() if v["fwhm_nm"]]
avg_fwhm_nm = sum(valid_fwhms_nm) / len(valid_fwhms_nm)
print(f"  Average FWHM: {avg_fwhm_nm:.4f} nm")

# ─────────────────────────────────────────────────────────────────────────────
# Step 3: Write corrected FWHM_Analysis file
# ─────────────────────────────────────────────────────────────────────────────
print(f"\n=== Step 3: Writing {os.path.basename(OUT_FWHM_FILE)} ===")
import datetime
date_str = datetime.datetime.now().strftime("%Y%m%d")
with open(OUT_FWHM_FILE, "w", encoding="utf-8") as f:
    f.write("# BBCEAS FWHM & Sigma Analysis Records\n")
    f.write(f"# Generated: {date_str} (CORRECTED — bug fix applied)\n")
    f.write("# Formula: abs(Sigma) = FWHM / 2.3548\n")
    f.write("# Note: Previous FWHM_Analysis.txt had FWHM=75.888nm due to algorithm bug.\n")
    f.write("#       Correct value is ~3.4nm (measured from raw Hg lamp spectrum).\n")
    f.write("-" * 60 + "\n")
    f.write("Pixel\tFWHM(nm)\tFWHM(px)\tabs_Sigma(nm)\tabs_Sigma(px)\n")
    for px in sorted(fwhm_records.keys()):
        d = fwhm_records[px]
        fnm, fpx = d["fwhm_nm"], d["fwhm_px"]
        snm, spx = fnm / 2.3548, fpx / 2.3548
        f.write(f"{px:.3f}\t{fnm:.4f}\t{fpx:.4f}\t{snm:.4f}\t{spx:.4f}\n")
print(f"  Saved: {OUT_FWHM_FILE}")

# ─────────────────────────────────────────────────────────────────────────────
# Step 4: Build interpolated sigma profile over all 2048 pixels
# ─────────────────────────────────────────────────────────────────────────────
ils_pixels = np.array([float(pk) for pk in fwhm_records.keys()])
ils_sigmas = np.array([v["sigma_nm"] for v in fwhm_records.values()])  # sigma in nm
f_sigma = interp1d(ils_pixels, ils_sigmas, kind="linear", fill_value="extrapolate")
pixel_indices = np.arange(len(wavelengths))
target_sigmas = f_sigma(pixel_indices)
print(f"\n  Sigma profile: min={target_sigmas.min():.4f} nm, max={target_sigmas.max():.4f} nm")

# ─────────────────────────────────────────────────────────────────────────────
# Step 5: ILS convolution helper
# ─────────────────────────────────────────────────────────────────────────────
HR_STEP = 0.002  # nm high-resolution grid step

def apply_dynamic_ils(raw_wave, raw_data, target_wl, sigmas_nm, lit_fwhm_nm=0.0):
    """Dynamic wavelength-dependent Gaussian ILS convolution."""
    hr_wave = np.arange(target_wl.min() - 5.0, target_wl.max() + 5.0, HR_STEP)
    f_raw = interp1d(raw_wave, raw_data, kind="linear", bounds_error=False, fill_value=0.0)
    hr_data = f_raw(hr_wave)

    lit_sigma = lit_fwhm_nm / 2.35482
    result = np.zeros(len(target_wl))

    for i, w in enumerate(target_wl):
        inst_sigma = sigmas_nm[i]
        added_var = max(1e-10, inst_sigma**2 - lit_sigma**2)
        kernel = (1.0 / np.sqrt(2 * np.pi * added_var)) * np.exp(
            -0.5 * (hr_wave - w) ** 2 / added_var
        )
        result[i] = float(np.sum(hr_data * kernel) * HR_STEP)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 6: Generate H2O from HITRAN
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Step 5a: Generating H2O from HITRAN ===")
h2o_wave, h2o_data = None, None
try:
    import hapi
    hapi.db_begin(HITRAN_DIR)
    w_min = wavelengths.min() - 10.0
    w_max = wavelengths.max() + 10.0
    nu_min = 1e7 / w_max  # cm^-1
    nu_max = 1e7 / w_min

    print(f"  Computing H2O absorption coeff {w_min:.1f}~{w_max:.1f} nm "
          f"({nu_min:.0f}~{nu_max:.0f} cm^-1)")
    nu_arr, coef = hapi.absorptionCoefficient_Voigt(
        SourceTables="H2O_Lines",
        Environment={"p": 1.0, "T": 293.0},
        OmegaStep=0.02,
        HITRAN_units=False,
    )
    wl_arr = 1e7 / nu_arr
    sort_i = np.argsort(wl_arr)
    h2o_wave = wl_arr[sort_i]
    h2o_data = coef[sort_i]
    mask = (h2o_wave >= w_min) & (h2o_wave <= w_max)
    h2o_wave, h2o_data = h2o_wave[mask], h2o_data[mask]
    print(f"  H2O: {len(h2o_wave)} points, max sigma = {h2o_data.max():.3e}")
except Exception as exc:
    print(f"  HITRAN failed ({exc}), using fallback near-zero H2O array")
    # Fallback: H2O is essentially transparent in 400-500 nm
    h2o_wave = np.linspace(wavelengths.min() - 5, wavelengths.max() + 5, 5000)
    h2o_data = np.full(len(h2o_wave), 1e-30)

RAW_XS["H2O-HITRAN"] = (h2o_wave, h2o_data)

# ─────────────────────────────────────────────────────────────────────────────
# Step 7: Load & convolve each cross-section, save reference files
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Step 6: Convolving and saving references ===")
sigma_results = {}   # gas → convolved array (for xlsx)

for gas, src in RAW_XS.items():
    print(f"\n  -- {gas} --")
    if isinstance(src, tuple):
        raw_wave, raw_data = src
    else:
        try:
            df_r = pd.read_csv(src, sep=r"\s+", header=None, comment="#")
            if len(df_r.columns) >= 2:
                raw_wave = pd.to_numeric(df_r.iloc[:, 0], errors="coerce").values
                raw_data = pd.to_numeric(df_r.iloc[:, 1], errors="coerce").values
            else:
                raise ValueError("Single-column cross-section without wavelength axis")
        except Exception as exc:
            print(f"    SKIP: failed to load {src}: {exc}")
            continue

    # Mask to finite values and crop to instrument range (with margin)
    ok = np.isfinite(raw_wave) & np.isfinite(raw_data)
    raw_wave, raw_data = raw_wave[ok], raw_data[ok]
    in_range = (raw_wave >= wavelengths.min() - 10) & (raw_wave <= wavelengths.max() + 10)
    if not np.any(in_range):
        print(f"    SKIP: no data in {wavelengths.min():.1f}~{wavelengths.max():.1f} nm")
        continue
    raw_wave, raw_data = raw_wave[in_range], raw_data[in_range]
    print(f"    Raw: {len(raw_wave)} pts, {raw_wave.min():.2f}~{raw_wave.max():.2f} nm, "
          f"max={raw_data.max():.3e}")

    print(f"    Applying ILS convolution (sigma ~{np.mean(target_sigmas):.3f} nm) ...")
    lit_fwhm = LIT_FWHM.get(gas, 0.0)
    result = apply_dynamic_ils(raw_wave, raw_data, wavelengths, target_sigmas, lit_fwhm)
    sigma_results[gas] = result

    out_name = f"Ref_{gas}_Dynamic-ILS-Applied(CAESAR cold,roi1).dat"
    out_path = os.path.join(COLD_DIR, out_name)
    header = (f"Generated by CAESAR Pro Ultimate\nGas: {gas}\nMath: Dynamic-ILS-Applied\n"
              f"Corrected: FWHM={avg_fwhm_nm:.4f}nm (was 75.888nm due to algorithm bug)")
    np.savetxt(out_path, result, fmt="%.8e", header=header)
    print(f"    Saved: {out_name}  ({len(result)} pts, max={result.max():.3e})")

    # Quick sanity check
    std_mean = result.std() / (result.mean() if result.mean() != 0 else 1)
    zeros = np.sum(result == 0.0)
    print(f"    Sanity: std/mean={std_mean:.3f}, zeros={zeros}")

# ─────────────────────────────────────────────────────────────────────────────
# Step 8: Save corrected sigma xlsx
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Step 7: Writing sigma(cold)_corrected.xlsx ===")
try:
    gas_order = ["CHOCHO", "H2O-HITRAN", "NO2", "O4"]
    n_header = 3
    n_data = len(wavelengths)
    # Build DataFrame matching original format: 4 groups × (data + 3 spacer cols) = 13 cols
    col_headers = ["CHOCHO", None, None, None, "H2O-HITRAN", None, None, None,
                   "NO2", None, None, None, "O4"]
    rows = []
    # Header rows
    rows.append(["# Generated by CAESAR Pro Ultimate"] + [None]*3 +
                ["# Generated by CAESAR Pro Ultimate"] + [None]*3 +
                ["# Generated by CAESAR Pro Ultimate"] + [None]*3 +
                ["# Generated by CAESAR Pro Ultimate"])
    rows.append([f"# Gas: CHOCHO"] + [None]*3 +
                [f"# Gas: H2O-HITRAN"] + [None]*3 +
                [f"# Gas: NO2"] + [None]*3 +
                [f"# Gas: O4"])
    rows.append(["# Math: Dynamic-ILS-Applied (CORRECTED)"] + [None]*3 +
                ["# Math: Dynamic-ILS-Applied (CORRECTED)"] + [None]*3 +
                ["# Math: Dynamic-ILS-Applied (CORRECTED)"] + [None]*3 +
                ["# Math: Dynamic-ILS-Applied (CORRECTED)"])
    for i in range(n_data):
        row = []
        for gas in gas_order:
            val = float(sigma_results[gas][i]) if gas in sigma_results else None
            row.extend([val, None, None, None])
        row = row[:13]  # only 13 cols (last group has no trailing spacers)
        rows.append(row)

    df_out = pd.DataFrame(rows)
    out_xlsx = os.path.join(COLD_DIR, "sigma(cold)_corrected.xlsx")
    df_out.to_excel(out_xlsx, index=False, header=False, engine="openpyxl")
    print(f"  Saved: {out_xlsx}")
except Exception as exc:
    print(f"  xlsx save failed: {exc}")

print("\n=== Done ===")
print(f"Summary:")
print(f"  Old FWHM: 75.888 nm (wrong, 20× too large due to FWHM_Analysis bug)")
print(f"  New FWHM: {avg_fwhm_nm:.4f} nm (correct, measured from Hg lamp raw data)")
print(f"  New sigma: {avg_fwhm_nm/2.3548:.4f} nm")
print(f"Files written to: {COLD_DIR}")
